### ISSUE TITLE
Get model object

### ISSUE THREAD

**Issue by devdjdjdj** [shankarpandala/lazypredict#229]
I couldn't find any methods to return the model objects that are trained.

Does lazypredict allow that? If yes, how ?

**Comment by shyamcody** [comment]
I went through the class codes of both lazyclassifier and lazyregressor and it seems that the table object is created using the fit() method in the classes but they don't return the model objects fitted. One solution could be done to accept a parameter called return_model where we would get the model_list also. I would request @shankarpandala to please take a look at this as it will make a good feature and establish lazypredict as a full pipeline instead of just for inspection purpose.

**Comment by shankarpandala** [comment]
@shyamcody If you can implement that please go ahead

**Comment by shyamcody** [comment]
I will try to create a pull request regarding this.

**Comment by shyamcody** [comment]
I have added PR #301 to solve this @shankarpandala . Can you please check and suggest if any change is needed?

**Comment by devdjdjdj** [comment]
@shankarpandala I see that this is added to the 0.2.8 milestone. Does the release have a timeline ?

**Comment by shankarpandala** [comment]
> @shankarpandala I see that this is added to the 0.2.8 milestone. Does the release have a timeline ?

I will do it next week
